imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false


########## SONATA

sonata_block:
        blocks:
            # enable the SonataAdminBundle block
            sonata.admin.block.admin_list:
                contexts: [ admin ]

sonata_admin:
    dashboard:
        blocks:
                -
                    position : left
                    type : sonata.admin.block.admin_list
                -
                    position : right
                    type : sonata.block.service.text
                    settings :
                        content : >
                            <h2>Welcome to the Sonata Admin</h2>
                            <p>This is a <code>sonata.block.service.text</code> from the Block
                            Bundle, you can create and add new block in these area by configuring
                            the <code>sonata_admin</code> section.</p> <br/> For instance, here
                            a RSS feed parser (<code>sonata.block.service.rss</code>):
                -
                    position : right
                    type : sonata.block.service.rss
                    roles : [ POST_READER ]
                    settings :
                        title : Sonata Project's Feeds
                        url : https://sonata-project.org/blog/archive.rss


                -
                    class :    col-lg-3 col-xs-6          # twitter bootstrap responsive code
                    position : top                        # zone in the dashboard
                    type :     sonata.admin.block.stats   # block id
                    settings :
                        code :  admin.category    # admin code - service id
                        icon :  fa-archive                    # font awesome icon
                        text :  app.category.stats            # static text or translation message
                        color : bg-yellow                 # colors : bg-green, bg-red and bg-aqua
                        filters :                         # filter values
                            edited : {  value : 1 }

                -
                     class :    col-lg-3 col-xs-6          # twitter bootstrap responsive code
                     position : top                        # zone in the dashboard
                     type :     sonata.admin.block.stats   # block id
                     settings :
                         code :  admin.blog_post   # admin code - service id
                         icon :  fa-archive               # font awesome icon
                         text :  app.blog_post.stats           # static text or translation message
                         color : bg-green               # colors : bg-green, bg-red and bg-aqua
                         filters :                         # filter values
                             edited : {  value : 1 }




    templates:
            layout:                     '@SonataAdmin/standard_layout.html.twig'
            ajax:                       '@SonataAdmin/ajax_layout.html.twig'
            list:                       '@SonataAdmin/CRUD/list.html.twig'
            show:                       '@SonataAdmin/CRUD/show.html.twig'
            show_compare:               '@SonataAdmin/CRUD/show_compare.html.twig'
            edit:                       '@SonataAdmin/CRUD/edit.html.twig'
            history:                    '@SonataAdmin/CRUD/history.html.twig'
            preview:                    '@SonataAdmin/CRUD/preview.html.twig'
            delete:                     '@SonataAdmin/CRUD/delete.html.twig'
            batch:                      '@SonataAdmin/CRUD/list__batch.html.twig'
            acl:                        '@SonataAdmin/CRUD/acl.html.twig'
            action:                     '@SonataAdmin/CRUD/action.html.twig'
            select:                     '@SonataAdmin/CRUD/list__select.html.twig'
            filter:                     '@SonataAdmin/Form/filter_admin_fields.html.twig'
            #dashboard:                  'test.html.twig'
            search:                     '@SonataAdmin/Core/search.html.twig'
            batch_confirmation:         '@SonataAdmin/CRUD/batch_confirmation.html.twig'
            inner_list_row:             '@SonataAdmin/CRUD/list_inner_row.html.twig'
            base_list_field:            '@SonataAdmin/CRUD/base_list_field.html.twig'
            list_block:                 '@SonataAdmin/Block/block_admin_list.html.twig'
            user_block:                 '@SonataAdmin/Core/user_block.html.twig'
            add_block:                  '@SonataAdmin/Core/add_block.html.twig'
            pager_links:                '@SonataAdmin/Pager/links.html.twig'
            pager_results:              '@SonataAdmin/Pager/results.html.twig'
            tab_menu_template:          '@SonataAdmin/Core/tab_menu_template.html.twig'
            history_revision_timestamp: '@SonataAdmin/CRUD/history_revision_timestamp.html.twig'
            short_object_description:   '@SonataAdmin/Helper/short-object-description.html.twig'
            search_result_block:        '@SonataAdmin/Block/block_search_result.html.twig'
            action_create:              '@SonataAdmin/CRUD/dashboard__action_create.html.twig'
            button_acl:                 '@SonataAdmin/Button/acl_button.html.twig'
            button_create:              '@SonataAdmin/Button/create_button.html.twig'
            button_edit:                '@SonataAdmin/Button/edit_button.html.twig'
            button_history:             '@SonataAdmin/Button/history_button.html.twig'
            button_list:                '@SonataAdmin/Button/list_button.html.twig'
            button_show:                '@SonataAdmin/Button/show_button.html.twig'